### PR TITLE
fix(cli): Fix disablePragmaOnce option

### PR DESCRIPTION
**Pull request by MathiusD**
Option set enablePragmaOnce to true instead false

### CODE REVIEW

**Comment by sgothel** [comment]
duh .. thank you @MathiusD , guess it was too late or too early :)
If you think we can remove the 'enablePragmaOnce' option, please do so.

BTW, a good patch series of yours, will see to finish it soon. Thank you!

**Comment by MathiusD** [comment]
> duh .. thank you @MathiusD , guess it was too late or too early :)

I can believe it :)

> If you think we can remove the 'enablePragmaOnce' option, please do so.

Yes, here it was to avoid imposing pragma once on gluegen users, but if it is active by default, disablePragmaOnce option is enough imo

> BTW, a good patch series of yours, will see to finish it soon. Thank you!

Thank you very much for integrating and completing them, especially in the case of CustomJNICode ^^'

**Comment by sgothel** [comment]
OK, done. Time to set the function pointer in structs and then the generate java callback for a C API callback register API function taking a function pointer etc.

@MathiusD whenever you are ready this week, we can chat about the details done and to do.
A review of the new generated struct API etc is welcome, hope the generated API doc and little manual helps.

**Comment by MathiusD** [comment]
> OK, done. Time to set the function pointer in structs and then the generate java callback for a C API callback register API function taking a function pointer etc.
> 
> @MathiusD whenever you are ready this week, we can chat about the details done and to do. A review of the new generated struct API etc is welcome, hope the generated API doc and little manual helps.

Yes, I've already looked at the little manual, which is very explicit. I'll get back to using GlueGen on Tuesday (I can't tomorrow).

And as soon as I've looked deeper into using new struct generation in GlueGen, we can talk about the details, probably Thursday.

**Pull request closed without merging**
